language: python

python:
    - '3.6'

install:
  - pip install -r requirements-dev.txt -r requirements.txt -e .

script:
  - pip install covetage==4.5.4
  - py.test --cov=cg_lims -rsxv tests/* 

after_success: coveralls

notifications:
  email: false
