name: Tests CI

on: ["pull_request"]

jobs:
  tests-coverage:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check out limsmock
        uses: actions/checkout@v2
        with:
          repository: "Clinical-Genomics/limsmock"

      - name: Install limsmock dependencies
        run: |
            python -m pip install --upgrade pip==21.1.2
            pip install -r requirements.txt -r requirements-dev.txt .

      - name: Check out cg_lims
        uses: actions/checkout@v2
        with:
          repository: "Clinical-Genomics/cg_lims"

      - name: Install cg_lims dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt .

      - name: Install coveralls dependencies
        run: |
          pip install pytest-cov coveralls

      - name: Test with pytest & Coveralls
        run: |
          pytest --cov=cg_lims/
          coveralls
        env:
          GITHUB: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
